#pragma once

#define ORYX_CONFIGURATOR

#define USB_SUSPEND_WAKEUP_DELAY 200

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61

#define LAYER_STATE_8BIT

#define TAPPING_TERM 220
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD

#define CAPS_WORD_IDLE_TIMEOUT 5000

#define RGB_MATRIX_STARTUP_SPD 60