#pragma once

#define ORYX_CONFIGURATOR
#define USB_SUSPEND_WAKEUP_DELAY 200
#define FIRMWARE_VERSION u8"DEVES01"
#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT
#define RGB_MATRIX_STARTUP_SPD 60

#define TAPPING_TERM 220
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define QUICK_TAP_TERM 0

#define ONESHOT_TIMEOUT 1800
#define ONESHOT_TAP_TOGGLE 3
