CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no

ORYX_ENABLE = yes

# Do not enable:
# RGB_MATRIX_CUSTOM_KB = yes